name: Continuous Integration

on:
  push:
    branches: [ ci-setup ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, pdo, pdo_pgsql
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Create .env.test from secrets
        run: |
          echo "KERNEL_CLASS='App\Kernel'" > .env.test
          echo "APP_SECRET='${{ secrets.APP_SECRET }}'" >> .env.test
          echo "DATABASE_URL=pgsql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost:5432/${{ secrets.DB_NAME }}_test?charset=utf8" >> .env.test

      # Installation manuelle de PostgreSQL et création de la base de données
      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql postgresql-contrib

      - name: Start PostgreSQL service
        run: |
          sudo service postgresql start

      - name: Create database manually
        run: |
          sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME}_test;"
          sudo -u postgres psql -c "CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';"
          sudo -u postgres psql -c "ALTER ROLE ${DB_USER} SET client_encoding TO 'utf8';"
          sudo -u postgres psql -c "ALTER ROLE ${DB_USER} SET default_transaction_isolation TO 'read committed';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME}_test TO ${DB_USER};"

      - name: Run database migrations
        run: php bin/console doctrine:migrations:migrate -n --env=test

      - name: Load fixtures
        run: php bin/console doctrine:fixtures:load -n --purge-with-truncate --env=test

      - name: Compile assets (Sass)
        run: php bin/console sass:build

      - name: Run tests
        run: php bin/phpunit

      - name: Static analysis
        run: php vendor/bin/phpstan
