name: Continuous Integration

on:
  push:
    branches: [ ci-setup ]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        options: --health-cmd="pg_isready -U postgres" --health-timeout=5s --health-retries=3 --health-start-period=30s
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_pgsql
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Create .env.test from secrets
        run: |
          echo "KERNEL_CLASS='App\Kernel'" > .env.test
          echo "APP_SECRET='${{ secrets.APP_SECRET }}'" >> .env.test
          echo "SYMFONY_DEPRECATIONS_HELPER=999999" >> .env.test
          echo "PANTHER_APP_ENV=panther" >> .env.test
          echo "PANTHER_ERROR_SCREENSHOT_DIR=./var/error-screenshots" >> .env.test
          echo "DATABASE_URL=pgsql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}?charset=utf8" >> .env.test

      # Step to create the test database (PostgreSQL style)
      - name: Create the test database
        run: |
          export PGPASSWORD=${{ secrets.DB_PASSWORD }}  # Pass the password to PGPASSWORD
          psql -h ${{ secrets.DB_HOST }} -U ${{ secrets.DB_USER }} -p ${{ secrets.DB_PORT }} -c "SELECT 'CREATE DATABASE ${{ secrets.DB_NAME }}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${{ secrets.DB_NAME }}')\gexec;"

      - name: Run database migrations
        run: php bin/console doctrine:migrations:migrate -n --env=test

      - name: Run tests
        run: php bin/phpunit

      - name: Static analysis
        run: php vendor/bin/phpstan
